# Netlify部署配置文件
# 支持零成本部署到Netlify平台

[build]
  # 构建命令
  command = "npm run build"
  # 构建输出目录
  publish = "dist"
  # 构建环境
  environment = {
    NODE_VERSION = "16"
  }

# 重写规则，确保单页应用路由正常工作
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 环境变量配置（生产环境）
[build.environment]
  # 在Netlify控制台设置这些敏感变量，这里只是示例
  # VITE_SUPABASE_URL = "你的Supabase URL"
  # VITE_SUPABASE_KEY = "你的Supabase密钥"

#  headers配置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"